
name: TOOLBOXLAP

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2022

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Random Password
      id: setpass
      run: |
        $charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        $password = -join ((1..12) | ForEach-Object { $charset[(Get-Random -Maximum $charset.Length)] })
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $password -Force)
        "Password: $password" | Out-File -Encoding utf8 rdp-password.txt

    - name: Commit password to GitHub
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add rdp-password.txt
        git commit -m "🔐 Update RDP password"
        git push

    - name: Start Playit
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

    - name: Keep session alive
      run: Start-Sleep -Seconds 21600
